spring:
  #给项目来个名字
  application:
    name: rabbitmq-test
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.10.30
    port: 5672
    username: admin
    password: admin
    #确认消息已发送到交换机(Exchange)
    # publisher-confirms: true
    #确认消息已发送到队列(Queue)
    # publisher-returns: true